global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'infra'
    static_configs:
      - targets: ['54.218.190.198:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['52.43.81.191:8080']
  - job_name: redis_exporter
    static_configs:
      - targets: ['52.43.81.191:9121']
  - job_name: nginx_exporter
    static_configs:
      - targets: ['52.43.81.191:9113']
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "rules.yml"
