groups:
- name: container-alerts
  rules:
  - alert: ContainerDown
    expr: up{job="cadvisor", container_name!="", container_name!="POD"} == 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Container {{ $labels.container_name }} is down"
      description: "Container {{ $labels.container_name }} on {{ $labels.instance }} is not running."

- alert: InfraMachineUnreachable
    expr: up{job="infra", instance="infra_ec2_private_ip:9100"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Infra machine is unreachable"
      description: "The Infra machine at {{ $labels.instance }} is unreachable. Please check the VM."
