groups:
- name: container-alerts
  rules:
  - alert: RedisDown
    expr: redis_up == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Redis down (instance {{ $labels.instance }})
      description: "Redis instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  - alert: nginxDOWN
    expr: nginx_up == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Nginx down (instance {{ $labels.instance }})
      description: "Nginx instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  - alert: InfraMachineUnreachable
    expr: up== 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "Infra machine is unreachable"
